/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 helmet.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props: any) {
  const { nodes, materials } = useGLTF('/model/helmet.glb') as any
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['node_damagedHelmet_-6514'].geometry} material={materials.Material_MR} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/model/helmet.glb')
